ALTER TABLE `activity` CHANGE `object_type` `object_type` ENUM('PROJECT','SCREEN','USER','MEASURE','COLOR','FONT','COMMENT','MODULE')  NOT NULL  DEFAULT 'PROJECT';
ALTER TABLE `activity` CHANGE `actor_type` `actor_type` ENUM('PROJECT','SCREEN','USER','MEASURE','COLOR','FONT','COMMENT','MODULE')  NOT NULL  DEFAULT 'PROJECT';
