<a class="logo" href="<?= R ?>">Clarify</a>
<?php
$projects = array();
if (is_array($_SESSION['user']['permissions']['project']) && sizeof($_SESSION['user']['permissions']['project']) > 0) {
    $projects = $db->data('SELECT id, creator, name, slug, screen_count FROM project WHERE id IN (' . implode(',', array_keys($_SESSION['user']['permissions']['project'])) . ') ORDER BY name ASC');
}
?>
<h3>Projects<a class="btn-add-project" href="javascript:;">+ Create</a></h3>
<div class="add-project">
    <input class="project-name" type="text" placeholder="Project Name" />
    <input class="add-project-submit" type="button" value="Create Project" />
</div>
<? if (sizeof($projects) == 0) { ?>
<div class="notice">You don't have any projects yet.</div>
<? } ?>
<ul>
    <? foreach ($projects as $p) { ?>
    <? 
    //$notifications = $p['id'] == 5 ? '<span class="notifications">5</span>' : ''; 
    ?>
    <li <?= $p['id'] == $project_id ? 'class="active"': '' ?>>
        <a href="<?= R ?>project/<?= $p['creator'] ?>/<?= $p['slug'] ?>/"><?= $p['name'] ?> <span class="count"><?= $p['screen_count'] ?></span><?= $notifications ?></a>
    </li>
    <? } ?>
</ul>
<!-- Project Settings -->
<? if ($project_id > 0) { ?>
<h3><?= $project['name'] ?></h3>
<ul>
    <li><a href="<?= R ?>guide/<?= $project_id ?>">Styleguide (Draft)</a></li>
    <? if (has_permission($project_id, 'ADMIN')) { ?>
    <li><a href="javascript:;" data-project="<?= $project_id ?>" data-name="<?= $project['name'] ?>" class="btn-rename-project">Rename Project</a></li>
    <li><a href="javascript:;" data-project="<?= $project_id ?>" class="btn-delete-project">Delete Project</a></li>
    <? } ?>
</ul>

<?php
$modules = $db->data("SELECT id, name FROM project_module WHERE project = '" . $project_id . "' ORDER BY name ASC");
?>
<h3>Module Library<? if (sizeof($modules) > 0) { ?><a href="javascript:;" class="btn-export-terrific">&#8677; Terrific</a><? } ?></h3>
<div class="modules">
    <? foreach ($modules as $module) { ?>
    <a href="javascript:;" data-module="<?= $module['name'] ?>" data-terrific="terrific:generate:module <?= $module['name'] ?>"></a>
    <? } ?>
</div>
<div class="notice">You have <?= sizeof($modules) ?> modules in your library.</div>
<? if (has_permission($project_id, 'ADMIN')) { ?>
<?php
$collaborators = $db->data('SELECT id, email FROM project_collaborator WHERE creator = ' . userid() . ' AND project = ' . $project_id . ' ORDER BY email ASC');
?>
<h3>
    Collaborators
    <a class="btn-add-collaborator" href="javascript:;">+ Add</a>
</h3>
<div class="add-collaborator">
    <input class="collaborator-email" data-project-id="<?= $project_id ?>" type="text" placeholder="E-Mail" />
    <input class="add-collaborator-submit" type="button" value="Add User" />
</div>
<? if (sizeof($collaborators) == 0) { ?>
    <div class="notice">You don't have any collaborators yet.</div>
<? } ?>
<ul class="collaborators">
    <? foreach ($collaborators as $c) { ?>
    <li>
        <div class="edit-collaborator" data-id="<?= $c['id'] ?>" href="#">
            <img src="<?= gravatar($c['email'], 24) ?>" width="24" height="24" />
            <span><?= $c['email'] ?></span>
            <a href="javascript:;" class="remove">&times;</a>
        </div>
    </li>
    <? } ?>
</ul>
<? } ?>
<? } ?>