<div class="signup">
    <div class="branding">
        <h2>Frontend Development Toolkit</p>
        <h1>Clarify</h1>
    </div>
    <div class="form">
        <? if ($route[2] > 0) { ?>
        <? $_SESSION['user']['invitation_code'] = intval($route[2]); ?>
        <input class="code" type="text" placeholder="Invitation Code" value="<?= intval($route[2]) ?>" />
        <a href="javascript:;" class="twitter">Create Account<span>with Twitter</span></a>
        <? } else { ?>
        <a href="javascript:;" class="twitter">Authenticate<span>with Twitter</span></a>
        <? } ?>
    </div>
    <div class="notice">&copy; 2012 clarify.io - a project by <a href="http://www.twitter.com/rogerdudler">Roger Dudler</a> &amp; <a href="http://www.namics.com">Namics</a>. Read the <a href="http://blog.clarify.io">Blog</a> or follow <a href="http://www.twitter.com/clarify_io">@clarify_io</a> on Twitter.
</div>
<div class="private-beta">Private Beta</div>