<a class="logo" href="<?php print R ?>">Clarify</a>
<div class="signup">
    <div class="form">
        <?php if ($route[2] > 0) { ?>
        <?php $_SESSION['user']['invitation_code'] = intval($route[2]); ?>
        <input class="code" type="text" placeholder="Invitation Code" value="<?php print intval($route[2]) ?>" />
        <a href="javascript:;" class="btn">Create Account</a>
        <?php } else { ?>
        <input class="email" type="text" placeholder="E-Mail" />
        <input class="password" type="password" placeholder="Password" />
        <div class="actions cf">
            <a href="javascript:;" class="btn btn-signin"><i class="icon icon-arrow-right"></i>&nbsp;&nbsp;Sign In</a>
            <a href="javascript:;" class="btn btn-twitter"><i class="icon icon-twitter"></i>&nbsp;&nbsp;Twitter</a>
        </div>
        <?php } ?>
    </div>
</div>
<div class="notice">
    &copy; 2012 <a href="http://clarify.io">clarify.io</a> - a project by 
    <a href="http://www.twitter.com/rogerdudler">@rogerdudler</a>. 
    follow <a href="http://www.twitter.com/clarify_io">@clarify_io</a> 
    for updates.
</div>
