<!-- Color Edit -->
<script id="tmpl-modal-color-edit" type="text/x-dot-template">
	<div class="head">
		<h2>Edit Color</h2>
	</div>
	<div class="body">
		{{?it.hex}}
		<div class="color" style="background: {{=it.hex}}"></div>
		{{?}}
		<label for="fld-name">Name</label>
		<input class="fld fld-name" id="fld-name" type="text" value="{{=it.name}}" />
		<label for="fld-hex">Hex Value</label>
		<input class="fld fld-hex" id="fld-hex" type="text" value="{{=it.hex}}" />
		<label for="fld-slug">Machine Name (for LESS &amp; SASS)</label>
		<input class="fld fld-slug" id="fld-slug" type="text" value="{{=it.slug}}" />
	</div>
	<div class="foot">
		<a class="btn btn-primary" href="javascript:;">Save</a>
		<a class="btn btn-delete" href="javascript:;">Delete Color</a>
		<a class="btn btn-cancel" href="javascript:;">Cancel</a>
	</div>
</script>