<!-- Create Set -->
<script id="tmpl-modal-create-set" type="text/x-dot-template">
	<div class="head">
		<h2><?= lang('btn_create_set') ?></h2>
	</div>
	<div class="body">
		<label for="fld-name">Name</label>
		<input class="fld fld-name" id="fld-name" type="text" placeholder="e.g. Mobile, Draft, Wireframes, etc." />
	</div>
	<div class="foot">
		<a class="btn btn-primary" href="javascript:;"><?= lang('btn_create_set') ?></a>
		<a class="btn btn-cancel" href="javascript:;"><?= lang('btn_cancel') ?></a>
	</div>
</script>