<!-- Screen Rename -->
<script id="tmpl-modal-rename-screen" type="text/x-dot-template">
	<div class="head">
		<h2>Rename Screen</h2>
	</div>
	<div class="body">
		<label for="fld-name">Screen Name</label>
		<input class="fld fld-name" id="fld-name" type="text" value="{{=it.name}}" />
	</div>
	<div class="foot">
		<a class="btn btn-primary" href="javascript:;">Rename</a>
		<a class="btn btn-cancel" href="javascript:;">Cancel</a>
	</div>
</script>