<!-- Module Edit -->
<script id="tmpl-modal-edit-module" type="text/x-dot-template">
    <div class="head">
        <h2>Edit Module</h2>
    </div>
    <div class="body">
        <label for="fld-name">Name</label>
        <input class="fld fld-name" id="fld-name" type="text" value="{{=it.name}}" />
    </div>
    <div class="foot">
        <a class="btn btn-primary" href="javascript:;">Save</a>
        <a class="btn btn-delete" href="javascript:;">Delete Module</a>
        <a class="btn btn-cancel" href="javascript:;">Cancel</a>
    </div>
</script>