<!-- Font Edit -->
<script id="tmpl-modal-font-edit" type="text/x-dot-template">
	<div class="head">
		<h2>Edit Font "{{=it.name}}"</h2>
	</div>
	<ul class="nav">
		<li class="active">
			<a href="#" data-tab="1">
				<span>Normal</span>
			</a>
		</li>
	</ul>
	<div class="body">
		<div class="tab tab-1">
			<label for="fld-name">Name</label>
			<input class="fld fld-name" id="fld-name" type="text" value="{{=it.name}}" />
			<label for="fld-family">Family</label>
			<input class="fld fld-family" id="fld-family" type="text" value="{{=it.family}}" />
			<label for="fld-color">Color (Hex)</label>
			<input class="fld fld-color" id="fld-color" type="text" value="#{{=it.color_hex}}" />
			<label for="fld-size">Size</label>
			<input class="fld fld-size" id="fld-size" type="text" value="{{=it.size}}" />
		</div>
	</div>
	<div class="foot">
		<a class="btn btn-primary" href="javascript:;">Save</a>
		<a class="btn btn-delete" href="javascript:;">Delete Font</a>
		<a class="btn btn-cancel" href="javascript:;">Cancel</a>
	</div>
</script>