<!-- Comment Layer: Share & Embed -->
<script id="tmpl-modal-comment-layer-share" type="text/x-dot-template">
	<div class="head">
		<h2>Share &amp; Embed</h2>
	</div>
	<div class="body">
		<label>Copy &amp; Paste the following snippet into your site and enable embedding</label>
		<pre>{{=it.code}}</pre>
	</div>
	<div class="foot">
		<a class="btn btn-primary" href="javascript:;">Enable Embedding</a>
		<a class="btn btn-cancel" href="javascript:;">Close</a>
	</div>
</script>