<!-- Font Edit -->
<script id="tmpl-modal-font-edit" type="text/x-dot-template">
	<div class="head">
		<h2>Edit Font "{{=it.name}}"</h2>
	</div>
	<div class="body">
		<input class="fld fld-name" id="fld-name" type="text" placeholder="Name" value="{{?it.name}}{{=it.name}}{{?}}" />
	</div>
	<ul class="nav">
		<li class="active">
			<a href="javascript:;" data-tab="1">
				<span>Normal</span>
			</a>
		</li>
		<li>
			<a href="javascript:;" data-tab="2">
				<span>Hover</span>
			</a>
		</li>
		<li>
			<a href="javascript:;" data-tab="3">
				<span>Active</span>
			</a>
		</li>
	</ul>
	<div class="body">
		<div class="tab tab-1">
			<input class="fld fld-font-family" id="fld-font-family" type="text" placeholder="Font Family, e.g. Arial, Helvetica, Lucida Grande, etc." value="{{?it.family}}{{=it.family}}{{?}}" />
			<input class="fld fld-font-color" id="fld-font-color" type="text" placeholder="Text Color, e.g. #000000" value="{{?it.color_hex}}{{=it.color_hex}}{{?}}" />
			<input class="fld fld-font-size" id="fld-font-size" type="text" placeholder="Font Size, e.g. 12px" value="{{?it.size}}{{=it.size}}{{?}}" />
			<input class="fld fld-font-line-height" id="fld-font-line-height" type="text" placeholder="Line Height, e.g. 1.4 (Factor)" value="{{?it.line_height}}{{=it.line_height}}{{?}}" />
		</div>
		<div class="tab tab-2">
			<input class="fld fld-hover-font-family" type="text" placeholder="Font Family, e.g. Arial, Helvetica, Lucida Grande, etc." value="{{?it.hover_family}}{{=it.hover_family}}{{?}}" />
			<input class="fld fld-hover-font-color" type="text" placeholder="Text Color, e.g. #000000" value="{{?it.color_hover_hex}}{{=it.color_hover_hex}}{{?}}" />
		</div>
		<div class="tab tab-3">
			<input class="fld fld-active-font-family" type="text" placeholder="Font Family, e.g. Arial, Helvetica, Lucida Grande, etc." value="{{?it.active_family}}{{=it.active_family}}{{?}}" />
			<input class="fld fld-active-font-color" type="text" placeholder="Text Color, e.g. #000000" value="{{?it.color_active_hex}}{{=it.color_active_hex}}{{?}}" />
		</div>
	</div>
	<div class="foot">
		<a class="btn btn-primary" href="javascript:;">Save</a>
		<a class="btn btn-delete" href="javascript:;">Delete Font</a>
		<a class="btn btn-cancel" href="javascript:;">Cancel</a>
	</div>
</script>