<div class="mod modModal">
	<div class="modal"></div>
	<a href="javascript:;" class="btn-close"><i class="icon icon-remove"></i></a>
</div>
<div class="mod modModalBackdrop"></div>
<?php require 'modal-project-settings.phtml'; ?>
<?php require 'modal-create-set.phtml'; ?>
<?php require 'modal-account-settings.phtml'; ?>
<?php require 'modal-rename-screen.phtml'; ?>
<?php require 'modal-delete-screen.phtml'; ?>
<?php require 'modal-delete-project.phtml'; ?>
<?php require 'modal-delete-set.phtml'; ?>
<?php require 'modal-export-terrific.phtml'; ?>
<?php require 'modal-export-color-library-less.phtml'; ?>
<?php require 'modal-export-color-library-sass.phtml'; ?>
<?php require 'modal-comment-layer-share.phtml'; ?>
<?php require 'modal-color-edit.phtml'; ?>
<?php require 'modal-font-edit.phtml'; ?>
<?php require 'modal-edit-dimension.phtml'; ?>
<?php require 'modal-edit-module.phtml'; ?>