<!-- Account Settings -->
<script id="tmpl-modal-account-settings" type="text/x-dot-template">
	<div class="head">
		<h2><?= lang('btn_profile_settings') ?></h2>
	</div>
	<div class="body">
		<label for="fld-name">Your Name</label>
		<input class="fld fld-name" id="fld-name" type="text" value="{{=it.name}}" />
		<label for="fld-email">Your E-Mail</label>
		<input class="fld fld-email" id="fld-email" type="text" value="{{=it.email}}" disabled="disabled" />
	</div>
	<div class="foot">
		<a class="btn btn-primary" href="javascript:;"><?= lang('btn_save') ?></a>
		<!--<a class="btn btn-delete" href="javascript:;">Delete Account</a>-->
		<a class="btn btn-cancel" href="javascript:;"><?= lang('btn_cancel') ?></a>
	</div>
</script>