<!-- Export: Terrific -->
<script id="tmpl-modal-export-terrific" type="text/x-dot-template">
	<div class="head">
		<h2>Export Modules to Terrific</h2>
	</div>
	<div class="body">
		<label>Execute the following commands within Terrific Composer</label>
		<pre>{{=it.code}}</pre>
		<label>or use this single command</label>
		<pre>{{=it.code_single}}</pre>
	</div>
	<div class="foot">
		<a class="btn btn-cancel" href="javascript:;">Close</a>
	</div>
</script>