<!-- Color Edit -->
<script id="tmpl-modal-edit-dimension" type="text/x-dot-template">
	<div class="head">
		<h2>Edit Dimensions</h2>
	</div>
	<div class="body">
		<label for="fld-width">Width</label>
		<input class="fld fld-width" id="fld-width" type="text" value="{{=it.width}}" />
		<label for="fld-height">Height</label>
		<input class="fld fld-height" id="fld-height" type="text" value="{{=it.height}}" />
	</div>
	<div class="foot">
		<a class="btn btn-primary" href="javascript:;">Save</a>
		<a class="btn btn-delete" href="javascript:;">Delete Dimension</a>
		<a class="btn btn-cancel" href="javascript:;">Cancel</a>
	</div>
</script>