<!-- Account Settings -->
<script id="tmpl-modal-account-settings" type="text/x-dot-template">
	<div class="head">
		<h2>Account Settings</h2>
	</div>
	<div class="body">
		<label for="fld-name">Your Name</label>
		<input class="fld fld-name" id="fld-name" type="text" value="{{=it.name}}" />
		<label for="fld-email">Your E-Mail</label>
		<input class="fld fld-email" id="fld-email" type="text" value="{{=it.email}}" disabled="disabled" />
	</div>
	<div class="foot">
		<a class="btn btn-primary" href="javascript:;">Save</a>
		<!--<a class="btn btn-delete" href="javascript:;">Delete Account</a>-->
		<a class="btn btn-cancel" href="javascript:;">Cancel</a>
	</div>
</script>