<!-- Module Edit -->
<script id="tmpl-modal-edit-module" type="text/x-dot-template">
    <div class="head">
        <h2>Edit Module</h2>
    </div>
    <div class="body">
        <label for="fld-name">Name</label>
        <input class="fld fld-name" id="fld-name" type="text" value="{{=it.name}}" />
        <!--
        <label for="fld-slug">Machine Name (for HTML/CSS)</label>
        <input class="fld fld-slug" id="fld-slug" type="text" value="{{=it.slug}}" />
        -->
    </div>
    <div class="foot">
        <a class="btn btn-primary" href="javascript:;">Save</a>
        <a class="btn btn-delete" href="javascript:;">Delete Module</a>
        <a class="btn btn-cancel" href="javascript:;">Cancel</a>
    </div>
</script>
<!-- Module Edit -->
<script id="tmpl-modal-edit-library-module" type="text/x-dot-template">
    <div class="head">
        <h2>Edit Library Module</h2>
    </div>
    <div class="body">
        <label for="fld-name">Name</label>
        <input class="fld fld-name" id="fld-name" type="text" value="{{=it.name}}" />
        <!--
        <label for="fld-slug">Machine Name (for HTML/CSS)</label>
        <input class="fld fld-slug" id="fld-slug" type="text" value="{{=it.slug}}" />
        -->
    </div>
    <div class="foot">
        <a class="btn btn-primary" href="javascript:;">Save</a>
        <a class="btn btn-cancel" href="javascript:;">Cancel</a>
    </div>
</script>