<form action="/">
    <fieldset>
        <label for="name">Name</label>
        <input type="text" id="name" class="form-text" />
        <p class="form-help">This is help text under the form field.</p>
    </fieldset>
    <fieldset class="check">
        <label><input type="checkbox" /> I accept the terms of service and lorem ipsum.</label>
    </fieldset>
    <fieldset class="form-actions">
        <input type="submit" value="Register &amp; Login with Twitter" />
    </fieldset>
</form>