<?php
if ($project_id > 0) {
    permission($project_id, 'VIEW');
    $screens = $db->data('
        SELECT 
            id, 
            project, 
            title, 
            width, 
            height, 
            ext, 
            created, 
            count_comment, 
            count_measure, 
            count_color, 
            count_font, 
            count_module
        FROM screen 
        WHERE project = ' . $project_id . ' 
        ORDER BY title ASC
    ');
    $project = $db->single("SELECT name FROM project WHERE id = '" . $project_id . "'");
}
?>
<div class="head">
    <h2><?= $project_id > 0 ? $project['name'] : 'Create or Choose a Project' ?></h2>
    <div class="usermeta">
        <div class="info">
            <p class="username"><?= user('name') ?></p>
            <a href="<?= R ?>auth/?wipe=1">Logout</a>
        </div>
        <div class="avatar">
            <img src="<?= $_SESSION['user']['twitter']->profile_image_url ?>" width="48" height="48" />
        </div>
    </div>
</div>
<? if ($project_id > 0) { ?>
<ul>
    <? if (has_permission($project_id, 'EDIT')) { ?>
    <li class="create">
        <a class="placeholder" href="javascript:;"><div></div></a>
        <p class="title-placeholder"><a href="#"><span>Click to upload screens</span></a></p>
        <p class="meta">JPG or PNG (max. 10 MB)</p>
    </li>
    <? } ?>
    <? foreach ($screens as $screen) { ?>
    <li class="screen screen-<?= $screen['id'] ?>">
        <a class="image" href="<?= R ?>screen/<?= $screen['id'] ?>">
            <img src="/upload/screens/<?= $project_id ?>/thumbnails/<?= md5($screen['id'] .config('security.general.hash')) ?>.<?= $screen['ext'] ?>" width="200" alt="" />
            <div class="info">
                <i class="icon-white icon-comment"></i> <span<?= $screen['count_comment'] == 0 ? ' class="zero"' : '' ?>><?= $screen['count_comment'] ?></span>
                <i class="icon-white icon-resize-vertical"></i> <span<?= $screen['count_measure'] == 0 ? ' class="zero"' : '' ?>><?= $screen['count_measure'] ?></span>
                <i class="icon-white icon-tint"></i> <span<?= $screen['count_color'] == 0 ? ' class="zero"' : '' ?>><?= $screen['count_color'] ?></span>
                <i class="icon-white icon-font"></i> <span<?= $screen['count_font'] == 0 ? ' class="zero"' : '' ?>><?= $screen['count_font'] ?></span>
                <i class="icon-white icon-th-large"></i> <span<?= $screen['count_module'] == 0 ? ' class="zero"' : '' ?>><?= $screen['count_module'] ?></span>
            </div>
        </a>
        <p class="title"><a href="javascript:;" data-screen="<?= $screen['id'] ?>" data-title="<?= $screen['title'] ?>"><span><?= htmlspecialchars(truncate($screen['title'],30,'...')) ?></span></a></p>
        <p class="meta">
            <span class="size"><?= $screen['width'] ?> &times; <?= $screen['height'] ?></span>
            <? if (has_permission($screen['project'], 'EDIT')) { ?>
            <a class="delete" data-screen="<?= $screen['id'] ?>" href="javascript:;">×</a>
            <? } ?>
        </p>
    </li>
    <? } ?>
</ul>
<input class="fileupload" type="file" name="files[]" multiple>
<? } else { ?>
<a class="btn-create-project" href="#">Create Project</a>
<? } ?>