<?php

if ($project_id > 0) {
    permission($project_id, 'VIEW');
    $set_slug = isset($route[4]) && $route[4] != '' ? $route[4] : false;
    $sets = array();
    if (!$set_slug) {
        $sets = $db->data('
            SELECT
                `set`.id,
                `set`.screen_count,
                `set`.name,
                `set`.slug,
                s.id as screen_id,
                s.ext as screen_ext
            FROM
                `set` 
                LEFT JOIN set_screen ss ON ss.`set` = `set`.id
                LEFT JOIN screen s ON s.id = ss.screen
            WHERE
                `set`.project = ' . $project_id . '
            GROUP BY
                `set`.id
            ORDER BY
                `set`.name ASC
        ');
        while(list($key, $set) = each($sets)) {
            if ($set['screen_count'] == 0) {
                $sets[$key]['image'] = "/img/empty-screen.png";
            } else {
                $sets[$key]['image'] = "/upload/screens/" . $project_id . "/thumbnails/" . md5($set['screen_id'] . config('security.general.hash')) . "." . $set['screen_ext'];
            }
        }
        $screens = $db->data('
            SELECT 
                s.id, 
                s.project, 
                s.title, 
                s.width, 
                s.height, 
                s.ext, 
                s.created, 
                s.count_comment, 
                s.count_measure, 
                s.count_color, 
                s.count_font, 
                s.count_module,
                ss.id as ss_id
            FROM screen s 
                LEFT JOIN set_screen ss ON ss.screen = s.id
            WHERE s.project = ' . $project_id . ' 
            GROUP BY s.id
            HAVING ss_id IS NULL
            ORDER BY s.title ASC
        ');
    } else {
        $set = $db->single("SELECT id, name FROM `set` WHERE slug = '" . $set_slug . "' AND project = " . $project_id);
        $screens = $db->data('
            SELECT 
                s.id, 
                s.project, 
                s.title, 
                s.width, 
                s.height, 
                s.ext, 
                s.created, 
                s.count_comment, 
                s.count_measure, 
                s.count_color, 
                s.count_font, 
                s.count_module
            FROM
                set_screen ss LEFT JOIN 
                screen s ON s.id = ss.screen
            WHERE ss.set = ' . $set['id'] . ' 
            ORDER BY s.title ASC
        ');
    }
    
    $project = $db->single("SELECT name, creator, slug, screen_background_color FROM project WHERE id = '" . $project_id . "'");
}

// load color library for this project
$colors = $db->data("
    SELECT id, hex, name, name_css 
    FROM project_color 
    WHERE project = '" . $project_id . "' 
    ORDER BY hue ASC
");

?>
<div class="head">
    <?php if ($project_id > 0) { ?>
        <?php if ($set) { ?>
            <h2><?php print $project['name'] ?> <span>&nbsp;<i class="icon icon-chevron-right"></i>&nbsp;&nbsp;<?php print $set['name'] ?></span></h2>
        <?php } else { ?>
            <h2><?php print $project['name'] ?></h2>
        <?php } ?>
    <?php } else { ?>
        <h2>&nbsp;</h2>
    <?php } ?>
    <?php if ($project_id > 0) { ?>
    <div class="actions">
        <?php if (has_permission($project_id, 'ADMIN')) { ?>
        <a href="javascript:;" class="btn-project-settings" 
            data-project="<?php print $project_id ?>" 
            data-name="<?php print $project['name'] ?>" 
            data-screen-background-color="<?php print $project['screen_background_color'] ?>">
            <i class="icon icon-cog"></i> <?= lang('btn_settings') ?></a>
        <?php } ?>
        <?php if (has_permission($project_id, 'EDIT') && !$set) { ?>
        <a href="javascript:;" class="btn-create-set" 
            data-project="<?php print $project_id ?>">
            <i class="icon icon-th"></i> <?= lang('btn_create_set') ?></a>
        <?php } ?>
    </div>
    <?php } ?>
    <div class="mod modUser">
        <?php require TERRIFIC . 'modules/User/user.phtml'; ?>
    </div>
</div>
<?php if ($project_id > 0) { ?>
<?php if (sizeof($colors) > 0) { ?>
<div class="colors">
    <?php foreach ($colors as $color) { ?>
    <a href="javascript:;" rel="tooltip" title="<?php print $color['name'] ?> – #<?php print $color['hex'] ?>" data-less="@<?php print $color['name_css'] ?>: #<?php print $color['hex'] ?>;" data-sass="$<?php print $color['name_css'] ?>: #<?php print $color['hex'] ?>;" data-hex="#<?php print $color['hex'] ?>" class="color color-<?php print $color['id'] ?>" style="background: #<?php print $color['hex'] ?>"></a>
    <?php } ?>
    <a href="javascript:;" class="export btn-export-css"><i class="icon icon-share-alt"></i> .LESS</a>
    <a href="javascript:;" class="export btn-export-sass"><i class="icon icon-share-alt"></i> .SASS</a>
    <a href="<?php print R ?>api/color/export/<?php print $project_id ?>/aco" class="export btn-export-aco"><i class="icon icon-share-alt"></i> .ACO</a>
</div>
<?php } ?>
<ul class="screens">
    <?php if (has_permission($project_id, 'EDIT')) { ?>
    <li class="create">
        <a class="placeholder" href="javascript:;">
            <div><i class="icon icon-upload"></i></div>
        </a>
        <p class="title-placeholder"><a href="#"><span><?= lang('btn_click_to_upload') ?></span></a></p>
        <p class="meta"><?= lang('txt_upload_format') ?></p>
    </li>
    <?php } ?>
    <?php foreach ($sets as $set) { ?>
    <li class="set" data-id="<?php print $set['id'] ?>">
        <a href="<?php print R . 'project/' . $project['creator'] . '/' . $project['slug'] . '/' . $set['slug'] ?>/">
            <div class="preview">
                <h4><?php print $set['name'] ?></h4>
                <img class="image-1" alt="" width="160" src="<?php print $set['image'] ?>" />
                <img class="image-2" alt="" width="160" src="<?php print $set['image'] ?>" />
            </div>
        </a>
        <p class="title"><a href="javascript:;" data-set="<?php print $set['id'] ?>" data-name="<?php print $set['name'] ?>"><?php print $set['name'] ?></a></p>
        <p class="meta">
            <span class="size screen_count"><?php print $set['screen_count'] ?> Screen(s)</span>
            <?php if (has_permission($project_id, 'EDIT')) { ?>
            <a class="delete delete-set" data-set="<?php print $set['id'] ?>" href="javascript:;">×</a>
            <?php } ?>
        </p>
    </li>
    <?php } ?>
    <?php if ($set_slug) { ?>
    <li class="set">
        <a href="<?php print R . 'project/' . $project['creator'] . '/' . $project['slug'] ?>">
            <div class="preview">
                <h4>All Screens</h4>
                <img class="image-1" alt="" width="160" src="<?php print R . 'img/empty-screen.png' ?>" />
                <img class="image-2" alt="" width="160" src="<?php print R . 'img/screen-overview.png' ?>" />
            </div>
        </a>
    </li>
    <?php } ?>
    <?php foreach ($screens as $screen) { ?>
    <li class="screen screen-<?php print $screen['id'] ?>" data-id="<?php print $screen['id'] ?>">
        <a class="image" href="<?php print R ?>screen/<?php print $screen['id'] ?>">
            <img src="/upload/screens/<?php print $project_id ?>/thumbnails/<?php print md5($screen['id'] .config('security.general.hash')) ?>.<?php print $screen['ext'] ?>" width="200" alt="Screen" />
            <div class="info">
                <span<?php print $screen['count_comment'] == 0 ? ' class="zero"' : '' ?>>
                    <i class="icon-white icon-comment"></i> <span class="count"><?php print $screen['count_comment'] ?></span>
                </span>
                <span<?php print $screen['count_measure'] == 0 ? ' class="zero"' : '' ?>>
                    <i class="icon-white icon-resize-vertical"></i> <span class="count"><?php print $screen['count_measure'] ?></span>
                </span>
                <span<?php print $screen['count_color'] == 0 ? ' class="zero"' : '' ?>>
                    <i class="icon-white icon-tint"></i> <span class="count"><?php print $screen['count_color'] ?></span>
                </span>
                <span<?php print $screen['count_font'] == 0 ? ' class="zero"' : '' ?>>
                    <i class="icon-white icon-font"></i> <span class="count"><?php print $screen['count_font'] ?></span>
                </span>
                <span<?php print $screen['count_module'] == 0 ? ' class="zero"' : '' ?>>
                    <i class="icon-white icon-th-large"></i> <span class="count"><?php print $screen['count_module'] ?></span>
                </span>
            </div>
        </a>
        <p class="title">
            <a href="javascript:;" data-screen="<?php print $screen['id'] ?>" data-title="<?php print $screen['title'] ?>">
                <span><?php print htmlspecialchars($screen['title']) ?></span>
            </a>
        </p>
        <p class="meta">
            <span class="size"><?php print $screen['width'] ?> &times; <?php print $screen['height'] ?></span>
            <?php if (has_permission($screen['project'], 'EDIT')) { ?>
            <a href="javascript:;" class="btn-replace" data-screen="<?php print $screen['id'] ?>"><?= lang('btn_replace') ?></a>
            <a class="delete delete-screen" data-screen="<?php print $screen['id'] ?>" href="javascript:;">×</a>
            <?php } ?>
        </p>
    </li>
    <?php } ?>
</ul>
<input class="fileupload" type="file" name="files[]" multiple>
<input class="fileupload-replace" type="file" name="files_replace[]">
<?php } else { ?>
<p class="intro">
    <strong>Clarify</strong> is a new way to manage &amp; share your design screens, whether they're wireframes or finished designs. Just <span>create a project</span> and <span>upload a screen</span> (png or jpg) to get started. We're still in beta, so please send feedback or report bugs to <a href="mailto:support@clarify.io?subject=Feedback">support@clarify.io</a>.
</p>
<a class="btn-create-project" href="#"><?= lang('btn_create_project') ?></a>
<?php } ?>

<!-- template for screen list items -->
<script id="tmpl-screenbrowser-screen" type="text/x-dot-template">
<li class="screen screen-{{=it.id}}" data-id="{{=it.id}}">
    <a class="image" href="<?php print R ?>screen/{{=it.id}}">
        {{?it.thumbnail_url}}
        <img src="{{=it.thumbnail_url}}" width="200" alt="{{=it.title}}" />
        {{?}}
        <div class="info">
            <span{{?it.count_comment == 0}} class="zero"{{?}}>
                <i class="icon-white icon-comment"></i> 
                <span class="count">{{=it.count_comment}}</span>
            </span>
            <span{{?it.count_measure == 0}} class="zero"{{?}}>
                <i class="icon-white icon-resize-vertical"></i> 
                <span class="count">{{=it.count_measure}}</span>
            </span>
            <span{{?it.count_color == 0}} class="zero"{{?}}>
                <i class="icon-white icon-tint"></i> 
                <span class="count">{{=it.count_color}}</span>
            </span>
            <span{{?it.count_font == 0}} class="zero"{{?}}>
                <i class="icon-white icon-font"></i> 
                <span class="count">{{=it.count_font}}</span>
            </span>
            <span{{?it.count_module == 0}} class="zero"{{?}}>
                <i class="icon-white icon-th-large"></i> 
                <span class="count">{{=it.count_module}}</span>
            </span>
        </div>
    </a>
    <p class="title">
        <a href="javascript:;" data-screen="{{=it.id}}" data-title="{{=it.title}}">
            <span>{{=it.title}}</span>
        </a>
    </p>
    <p class="meta">
        <span class="size">{{?it.width}}{{=it.width}} &times; {{=it.height}}{{??}}Uploading...{{?}}</span>
        {{?it.editable}}
        <a href="javascript:;" class="btn-replace" data-screen="{{=it.id}}">Replace</a>
        <a class="delete delete-screen" data-screen="{{=it.id}}" href="javascript:;">×</a>
        {{?}}
    </p>
</li>
</script>