<div class="section section-nav">
<a class="button btn-screen" href="<?php print R ?>project/<?php print $screen['project_creator'] ?>/<?php print $screen['project_slug'] ?>/">
	<i class="icon icon-arrow-left"></i>
	<div class="tt"><?php echo lang('btn_back') ?></div>
</a>
</div>
<div class="section section-tool">
	<a class="button btn-comments" href="javascript:;">
		<i class="icon icon-comment"></i>
		<div class="tt"><?php echo lang('layer_annotations') ?></div>
		<?php if ($screen['count_comment'] > 0) { ?>
		<div class="count"><?php echo $screen['count_comment'] ?></div>
		<?php } ?>
	</a>
	<a class="button btn-measure" href="javascript:;">
		<i class="icon icon-resize-vertical"></i>
		<div class="tt"><?php echo lang('layer_measures') ?></div>
		<?php if ($screen['count_measure'] > 0) { ?>
		<div class="count"><?php echo $screen['count_measure'] ?></div>
		<?php } ?>
	</a>
	<a class="button btn-color" href="javascript:;">
		<i class="icon icon-tint"></i>
		<div class="tt"><?php echo lang('layer_colors') ?></div>
		<?php if ($screen['count_color'] > 0) { ?>
		<div class="count"><?php echo $screen['count_color'] ?></div>
		<?php } ?>
	</a>
	<a class="button btn-fonts" href="javascript:;">
		<i class="icon icon-font"></i>
		<div class="tt"><?php echo lang('layer_typography') ?></div>
		<?php if ($screen['count_font'] > 0) { ?>
		<div class="count"><?php echo $screen['count_font'] ?></div>
		<?php } ?>
	</a>
	<a class="button btn-modules btn-last" href="javascript:;">
		<i class="icon icon-th-large"></i>
		<div class="tt"><?php echo lang('layer_modules') ?></div>
		<?php if ($screen['count_module'] > 0) { ?>
		<div class="count"><?php echo $screen['count_module'] ?></div>
		<?php } ?>
	</a>
</div>
<div class="section section-settings">
<?php if (has_permission($screen['project'], 'ADMIN')) { ?>
<a class="button btn-embed" href="javascript:;" data-screen="<?php print $screen['id'] ?>" data-url="<?php print config('application.domain') . R . 'embed/' . $screen['code'] . '/800' ?>"><i class="icon icon-share"></i><div class="tt">Embed &amp; Share</div>
	<?php if ($screen['embeddable']) { ?>
	<span class="enabled">&#9679;</span>
	<?php } ?>
</a>
<?php } ?>
</div>
