<a class="button btn-screen" href="<?= R ?>project/<?= $screen['project'] ?>"><i class="icon-white icon-th-list"></i> Screens</a>
<a class="button btn-embed" href="javascript:;" data-screen="<?= $screen['id'] ?>" data-url="<?= config('application.domain') . R . 'embed/' . $screen['id'] . '/800' ?>"><i class="icon-white icon-share-alt"></i> Embed</a>
<a class="button btn-delete" href="javascript:;"><i class="icon-white icon-trash"></i> Delete</a>
<a class="button btn-color btn-last" href="javascript:;"><i class="icon-white icon-tint"></i> Colors</a>
<a class="button btn-measure" href="javascript:;"><i class="icon-white icon-th-large"></i> Measures</a>
<a class="button btn-comments" href="javascript:;"><i class="icon-white icon-comment"></i> Comments</a>