<a class="button btn-logo" href="?view=browser">&nbsp;</a>
<a class="button btn-screen" href="?view=browser&amp;project=<?= $screen['project'] ?>">Screens</a>
<a class="button btn-delete" href="javascript:;">Delete</a>
<!--<a class="button btn-clear" href="javascript:;">Clear all</a>-->
<a class="button btn-color" href="javascript:;">Colors</a>
<a class="button btn-measure" href="javascript:;">Measure</a>
<a class="button btn-comments" href="javascript:;">Comments</a>