<div class="mod modSidebar">
	<ul class="nav clearfix">
		<li class="tab-comment active"><a href="#"><i class="icon icon-comment"></i></a></li>
		<li class="tab-color"><a href="#"><i class="icon icon-tint"></i></a></li>
	</ul>
	<div class="items items-comments"></div>
	<div class="items items-colors">
		<?php foreach ($colors as $color) { ?>
		<div class="item item-<?php echo $color['id'] ?> clearfix">
			<div class="color" style="background: #<?php echo $color['hex'] ?>"></div>
			<div class="title">
				<span class="name"><?php echo $color['name'] ?></span>
				<span class="hex">#<?php echo $color['hex'] ?></span>
			</div>
		</div>
		<?php } ?>
	</div>
</div>

<script id="tmpl-sidebar-comment" type="text/x-dot-template">
<div class="item item-{{=it.id}}">
	<div class="author clearfix">
		<div class="nr">{{=it.nr}}</div>
		<!--<img src="<?php print gravatar(user('email'), 32) ?>" width="16" height="16" />-->
		<p>Roger Dudler</p>
	</div>
	<p class="content">{{?it.content}}{{=it.content}}{{??}}<i>Empty</i>{{?}}</p>
</div>
</script>

<script id="tmpl-sidebar-color" type="text/x-dot-template">
<div class="item item-{{=it.id}} clearfix">
	<div class="color" style="background: #{{=it.hex}}"></div>
	<div class="title">
		<span class="name">Sapphire</span>
		<span class="hex">#{{=it.hex}}</span>
	</div>
</div>
</script>