<div class="mod modSidebar">
<div class="items items-comments">
	
</div>
</div>

<script id="tmpl-sidebar-comment" type="text/x-dot-template">
<div class="item item-{{=it.id}}">
	<div class="author clearfix">
		<div class="nr">{{=it.nr}}</div>
		<!--<img src="<?php print gravatar(user('email'), 32) ?>" width="16" height="16" />-->
		<p>Roger Dudler</p>
	</div>
	<p class="content">{{?it.content}}{{=it.content}}{{??}}<i>Empty</i>{{?}}</p>
</div>
</script>